/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreakdownDiagnosisPanel: typeof import('./src/components/BreakdownDiagnosisPanel.vue')['default']
    CustomerTrackingTimeline: typeof import('./src/components/CustomerTrackingTimeline.vue')['default']
    FeedbackModal: typeof import('./src/components/FeedbackModal.vue')['default']
    ForceCloseButton: typeof import('./src/components/ForceCloseButton.vue')['default']
    HealthScoreCard: typeof import('./src/components/HealthScoreCard.vue')['default']
    InventoryRequestPanel: typeof import('./src/components/InventoryRequestPanel.vue')['default']
    JobCardCreationWizard: typeof import('./src/components/JobCardCreationWizard.vue')['default']
    MaintenanceJobTable: typeof import('./src/components/MaintenanceJobTable.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ReopenButton: typeof import('./src/components/ReopenButton.vue')['default']
    RepairJobTable: typeof import('./src/components/RepairJobTable.vue')['default']
    RoleBoundary: typeof import('./src/components/RoleBoundary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoftwareUpdatePanel: typeof import('./src/components/SoftwareUpdatePanel.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    SubsystemPicker: typeof import('./src/components/SubsystemPicker.vue')['default']
    Wizard: typeof import('./src/components/Wizard.vue')['default']
  }
}
